#!/usr/bin/env bash
#World Wide Web
#Function to display information about a subdomain
display_info() {
  local domain=$1
  local subdomain=$2
  local rtype
  rtype=$(dig "$subdomain"."$domain" | awk '/ANSWER SECTION/ {getline; print $4}')
  local dest
  dest=$(dig "$subdomain"."$domain" | awk '/ANSWER SECTION/ {getline; print $5}')
  echo "The subdomain $subdomain is a $rtype record and points to $dest"
}

#check if both domain and subdomain parameters are provided
if [[ $# -eq 2 ]]; then
  display_info "$1" "$2"
else
  subdomains=("www" "lb-01" "web-01" "web-02")

  for subdomain in "${subdomains[@]}"; do
    display_info "$1" "$subdomain"
  done
fi
