#!/usr/bin/env bash/Alx-Projects/alx-system_engineering-devops/0x0C-web_server# ls
# Install nginx web server_nginx_web_server  2-setup_a_domain_name  3-redirection  README.md  some_page.html
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
sudo chown -R "$USER":"$USER" /var/www/html/index.nginx-debian.html
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i '51i\               if ($request_filename ~ redirect_me){\n                         rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n          }' /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" > sudo tee /var/www/html/404.html
sudo sed -i '47i\.0     error_page 404 /404.html;' /etc/nginx/sites-enabled/default
sudo service nginx restart
