#!/usr/bin/env bash
# This script is displaying "Best School" 10 times,
# but for the 9th iteration, displays Best School and then Hi on a new line.

#!/usr/bin/env bash
# Displays "Holberton School" 10 times using a while loop.
#   On the 9th iteration, displays "Hi" before "Holberton School".

i=0

while [ $i -lt 10 ]
do
  if [ $i -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( i++ ))
done
